# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get numeric vector from python __main__ namespace.
#' 
#' The data retrieved from Python has to be a list of numbers.
#' 
#' @param name Python variable name
#' 
#' @export
numvec_to_R <- function(name) {
    .Call('spacyr_numvec_to_R', PACKAGE = 'spacyr', name)
}

#' Copy list of strings from Python to R character vector
#' 
#' @examples
#'
#'pyrun("l = ['a', 'b']")
#'pyrun("print(l)")
#'charvec_to_R("l")
#'pyrun("l2 = [u'a', u'b']")
#'charvec_to_R("l2")
#' @param name Python variable name
#' 
#' @export
charvec_to_R <- function(name) {
    .Call('spacyr_charvec_to_R', PACKAGE = 'spacyr', name)
}

char_to_R <- function(name) {
    .Call('spacyr_char_to_R', PACKAGE = 'spacyr', name)
}

num_to_R <- function(name) {
    .Call('spacyr_num_to_R', PACKAGE = 'spacyr', name)
}

#' Run python code
#'
#' Runs Python code in namespace __main__ . 
#' 
#' @param command Python code to execute as string
#' @examples
#' pyrun("print(range(5))")
#' @export
pyrun <- function(command) {
    invisible(.Call('spacyr_pyrun', PACKAGE = 'spacyr', command))
}

py_initialize <- function(pythonSharedLibrary) {
    invisible(.Call('spacyr_py_initialize', PACKAGE = 'spacyr', pythonSharedLibrary))
}

finalize_python <- function() {
    invisible(.Call('spacyr_finalize_python', PACKAGE = 'spacyr'))
}

#' Push data to python __main__ namespace
#' 
#' @param name Python variable name as string
#' @param x Numeric vector to copy to Python
topy.numeric <- function(x, name) {
    invisible(.Call('spacyr_numvec_to_python', PACKAGE = 'spacyr', x, name))
}

topy.character <- function(strings, name) {
    invisible(.Call('spacyr_charvec_to_python', PACKAGE = 'spacyr', strings, name))
}

pydict.numeric <- function(x, name, dictname) {
    invisible(.Call('spacyr_num_to_dict', PACKAGE = 'spacyr', x, name, dictname))
}

pydict.character <- function(x, name, dictname) {
    invisible(.Call('spacyr_char_to_dict', PACKAGE = 'spacyr', x, name, dictname))
}

